using System.Drawing;

namespace CTIToolkit
{
    static class Globals
    {
        public static Color[] CTI_Palette = {
                        Color.FromArgb(65, 140, 240),
                        Color.FromArgb(252, 180, 65),
                        Color.FromArgb(224, 64, 10),
                        Color.ForestGreen,
                        Color.Purple,
                        Color.Navy,
                        Color.Goldenrod,
                        Color.DarkSeaGreen,
                        Color.OliveDrab,
                        Color.Chocolate,
                        Color.Firebrick,
                        Color.Olive,
                        Color.SandyBrown,
                        Color.LightSeaGreen,
                        Color.Yellow,
                        Color.SaddleBrown,
                        Color.FromArgb(5, 100, 146),
                        Color.FromArgb(26, 59, 105),
                        Color.Green,
                        Color.FromArgb(255, 227, 130),
                        Color.Plum,
                        Color.CadetBlue,
                        Color.FromArgb(18, 156, 221),
                        Color.FromArgb(202, 107, 75),
                        Color.FromArgb(0, 92, 219),
                        Color.FromArgb(243, 210, 136),
                        Color.FromArgb(80, 99, 129),
                        Color.FromArgb(241, 185, 168),
                        Color.FromArgb(224, 131, 10),
                        Color.FromArgb(120, 147, 190),
                        Color.Peru,
                        Color.Blue,
                        Color.Lime,
                        Color.Fuchsia,
                        Color.Teal,
                        Color.Aqua,
                        Color.Navy,
                        Color.Maroon,
                        Color.Red,
                        Color.Olive,
                        Color.Tomato,
                        Color.SkyBlue,
                        Color.LimeGreen,
                        Color.MediumOrchid,
                        Color.LightCoral,
                        Color.SteelBlue,
                        Color.YellowGreen,
                        Color.Turquoise,
                        Color.HotPink,
                        Color.Khaki,
                        Color.Tan,
                        Color.DarkSeaGreen,
                        Color.CornflowerBlue,
                        Color.PeachPuff,
                        Color.LightSalmon
                    };
    }
}
